"""
models/database.py  –  SQLAlchemy async models for MemVault
"""
from datetime import datetime
from sqlalchemy import (
    Column, String, Integer, Float, Boolean,
    DateTime, ForeignKey, Text, JSON
)
from sqlalchemy.orm import relationship, DeclarativeBase
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    database_url: str = "sqlite+aiosqlite:///./memvault.db"
    secret_key: str = "change-me-in-production"
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 10080
    google_client_id: str = ""
    google_client_secret: str = ""
    google_redirect_uri: str = "http://localhost:8000/auth/google/callback"
    openai_api_key: str = ""
    compression_quality: int = 82
    max_upload_mb: int = 500
    allowed_origins: str = "http://localhost:3000"

    class Config:
        env_file = ".env"


settings = Settings()

engine = create_async_engine(settings.database_url, echo=False)
AsyncSessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


# ─── User ────────────────────────────────────────────────────────────────────
class User(Base):
    __tablename__ = "users"

    id              = Column(String, primary_key=True)          # Google sub
    email           = Column(String, unique=True, index=True, nullable=False)
    display_name    = Column(String)
    avatar_url      = Column(String)
    google_token    = Column(Text)                              # JSON-encoded OAuth token
    drive_folder_id = Column(String)                            # MemVault root folder on Drive
    created_at      = Column(DateTime, default=datetime.utcnow)
    plan            = Column(String, default="free")            # free | pro

    memories        = relationship("Memory", back_populates="owner", cascade="all, delete-orphan")
    family_memberships = relationship("FamilyMember", back_populates="user", cascade="all, delete-orphan")
    owned_vaults    = relationship("FamilyVault", back_populates="owner", cascade="all, delete-orphan")


# ─── Memory ──────────────────────────────────────────────────────────────────
class Memory(Base):
    __tablename__ = "memories"

    id              = Column(String, primary_key=True)
    owner_id        = Column(String, ForeignKey("users.id"), index=True)
    title           = Column(String, nullable=False)
    description     = Column(Text)
    mime_type       = Column(String)                            # image/avif, video/mp4, etc.
    original_size   = Column(Integer)                           # bytes before compression
    stored_size     = Column(Integer)                           # bytes after compression
    drive_file_id   = Column(String)                            # Google Drive file ID
    drive_thumb_id  = Column(String)                            # Thumbnail Drive file ID
    thumbnail_url   = Column(String)
    taken_at        = Column(DateTime)
    uploaded_at     = Column(DateTime, default=datetime.utcnow)
    tags            = Column(JSON, default=list)                # ["beach","family","2022"]
    ai_tags         = Column(JSON, default=list)                # Auto-generated by GPT Vision
    location        = Column(String)
    is_duplicate    = Column(Boolean, default=False)
    album_id        = Column(String, ForeignKey("albums.id"), nullable=True)
    shared_with     = Column(JSON, default=list)                # list of vault IDs

    owner           = relationship("User", back_populates="memories")
    album           = relationship("Album", back_populates="memories")


# ─── Album ───────────────────────────────────────────────────────────────────
class Album(Base):
    __tablename__ = "albums"

    id          = Column(String, primary_key=True)
    owner_id    = Column(String, ForeignKey("users.id"))
    name        = Column(String, nullable=False)
    cover_url   = Column(String)
    created_at  = Column(DateTime, default=datetime.utcnow)
    memories    = relationship("Memory", back_populates="album")


# ─── Family Vault ────────────────────────────────────────────────────────────
class FamilyVault(Base):
    __tablename__ = "family_vaults"

    id          = Column(String, primary_key=True)
    owner_id    = Column(String, ForeignKey("users.id"))
    name        = Column(String, nullable=False)               # "The Sharma Family"
    invite_code = Column(String, unique=True, index=True)
    created_at  = Column(DateTime, default=datetime.utcnow)

    owner       = relationship("User", back_populates="owned_vaults")
    members     = relationship("FamilyMember", back_populates="vault", cascade="all, delete-orphan")


# ─── Family Member ───────────────────────────────────────────────────────────
class FamilyMember(Base):
    __tablename__ = "family_members"

    id          = Column(String, primary_key=True)
    vault_id    = Column(String, ForeignKey("family_vaults.id"))
    user_id     = Column(String, ForeignKey("users.id"))
    role        = Column(String, default="viewer")             # owner | editor | viewer
    joined_at   = Column(DateTime, default=datetime.utcnow)

    vault       = relationship("FamilyVault", back_populates="members")
    user        = relationship("User", back_populates="family_memberships")


async def init_db():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def get_db():
    async with AsyncSessionLocal() as session:
        yield session
